version: "3.9"
services:
    telegraf:
        build:
            context: .
            dockerfile: Dockerfile-telegraf
        ports:
            - "9273:9273"
        env_file:
            - .env
    prometheus:
        build:
            context: .
            dockerfile: Dockerfile-prometheus
        ports:
            - "9090:9090"
        depends_on:
            - "telegraf"
    grafana:
        build: ./grafana
        container_name: ${CONTAINER_PREFIX}_grafana
        ports: 
            - ${GRAFANA_PORT}:${GRAFANA_PORT}
        links:
            - prometheus
        volumes:
            - /var/lib/grafana
            - /var/log/grafana
            - /var/lib/grafana/plugins
        restart: always
        env_file:
            - .env
